version: '3'
services:
  strapi:
    image: strapi/strapi
    volumes:
      - ./app:/srv/app
    restart: unless-stopped
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201" # Logstash UDP input port
        tag: "strapi-friendly"
    networks:
      default:
        aliases:
        - friendlydevco_strapi
networks:
    default:
       external:
         name: webproxy